CREATE EXTENSION postgis;


create table public.trees
(
    id                  bigint generated by default as identity
        primary key
        unique,
    location            bigint                 not null,
    location_addition   varchar,
    current_number      bigint,
    chopped             boolean,
    trunk_diameter      double precision,
    trunk_circumference double precision,
    crown_diameter      double precision,
    crown_circumference double precision,
    height              double precision,
    tree_group          bigint,
    district_reference  varchar,
    district_number     bigint,
    district_name       varchar,
    outside_reference   varchar,
    object_number       bigint,
    object_name         varchar,
    tree_type_reference varchar,
    tree_type_botanic   varchar,
    tree_type_german    varchar,
    tree_type_short     varchar,
    outdoor_reference   varchar,
    care_number         bigint,
    care_type           varchar,
    trunk_radius        double precision,
    crown_radius        double precision,
    geocoordinates      geography(Point, 4326) not null
);

comment on table public.trees is 'Alle Informationen über die Bielefelder Bäume.';

alter table public.trees
    owner to postgres;

grant select, update, usage on sequence public.trees_id_seq to anon;

grant select, update, usage on sequence public.trees_id_seq to authenticated;

grant select, update, usage on sequence public.trees_id_seq to service_role;

create index trees_geocoordinates
    on public.trees using gist (geocoordinates);

grant delete, insert, references, select, trigger, truncate, update on public.trees to anon;

grant delete, insert, references, select, trigger, truncate, update on public.trees to authenticated;

grant delete, insert, references, select, trigger, truncate, update on public.trees to service_role;

create policy "Enable read access for all users" on "public"."trees" as permissive for select to public using (true);